---
# file: roles/vagrant/tasks/main.yml

- name: ensure that the virtualbox guest extensions are present
  get_url: >
    url=http://download.virtualbox.org/virtualbox/4.3.6/VBoxGuestAdditions_4.3.6.iso
    dest=/home/vagrant/VBoxGuestAdditions_4.3.6.iso
    mode=0666
