---
# file: roles/registry/tasks/main.yml

- name: ensure required packages are present
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - couchdb
    - nodejs
    - npm
    - rabbitmq-server

- name: ensure the couchdb configuration file is present
  copy: src=etc/couchdb/local.ini dest=/etc/couchdb/local.ini mode=0640
