---
- name: setup a node.js node
  hosts: all
  gather_facts: no
  sudo: yes

  tasks:
    - name: ensure required packages are present
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - couchdb
        - mandelbulber
        - nodejs
        - npm
        - rabbitmq-server
        - vim
      notify: poweroff node

    - name: ensure that vim is the default editor
      shell: update-alternatives --set editor /usr/bin/vim.basic
 
    - name: ensure that the virtualbox guest extensions are present
      get_url: >
        url=http://download.virtualbox.org/virtualbox/4.3.6/VBoxGuestAdditions_4.3.6.iso
        dest=/home/vagrant/VBoxGuestAdditions_4.3.6.iso
        mode=0666

  handlers:
    - name: poweroff node
      shell: poweroff
