
- hosts: all
  gather_facts: no
  sudo: yes
  roles:
    - role: common

- hosts: api
  gather_facts: no
  sudo: yes
  roles:
    - role: api

- hosts: generator
  gather_facts: no
  sudo: yes
  roles:
    - role: generator

- hosts: registry
  gather_facts: no
  sudo: yes
  roles:
    - role: registry

- hosts: store
  gather_facts: no
  sudo: yes
  roles:
    - role: store
